README.md, examples/concat.clar, src/ast_visitor.rs, src/standard/standard.wat, src/wasm_generator.rs
- Add stack management
- Variables that require stack allocation can be allocated onto the stack.
The stack is managed by a new function prelude/postlude.
- Support creating a block in the Wasm
- This is used initially for containing all of the code in a function, so
that all exits from the function can easily exit the block and execute
the function postlude before leaving the function. Doing this required a
significant refactoring, to allow us to the `InstrSeqBuilder` around and
avoid problems from the borrow checker.
=> Stack management

.github/workflows/audit-on-new-deps.yaml, .github/workflows/ci.yaml, .github/workflows/daily-checks.yaml
This PR adds some CI to the repo:
- on each new PR against main, we run the tests, check formatting and check for the absence of clippy warnings
- on each push to main, same checks
- on change in Cargo.toml or Cargo.lock, we run cargo-audit
- every day, we run cargo-audit and check for clippy warnings (in case there would be new ones after a toolchain update).
Closes #12
=> Add CI tasks

tests/tests/lib_tests.rs
This is a refactor of the the _lib\_tests_, where all the common parts in the tests are now hidden in a `test_contract` macro.
=> refactor: remove tests boilerplate by macroizing the common parts

clar2wasm/src/wasm_generator.rs, tests/contracts/begin.clar, tests/tests/lib_tests.rs
The non-obvious feature here is to throw away unused return values for the statements in the list, except for the last one, whose return value becomes the return value for the `begin` expression.
=> feat: add support for `begin` expression

clar2wasm/src/standard/standard.wat, clar2wasm/src/wasm_generator.rs, clar2wasm/tests/standard/property_tests.rs, clar2wasm/tests/standard/unit_tests.rs, tests/src/lib.rs, tests/tests/lib_tests.rs
Fixes #49 
This PR reverses the passing order of high and low parts of int and uint, to give them a better little-endianness feeling.
=> Chore: invert low and high in litteral values int and uint

clar2wasm/src/ast_visitor.rs, clar2wasm/src/wasm_generator.rs
This PR has ~two~ one goal~s~:
- removing the useless lifetime in ASTVisitor,
~- changing the methods to not take a builder by value anymore, but as a mutable reference (this is useful if we want to create a dangling builder).~
UPDATE: I changed the original purpose of this PR. The change about lifetimes is big enough.
=> Removal of the useless lifetime parameter of ASTVisitor

clar2wasm/tests/standard/property_tests.rs, clar2wasm/tests/standard/utils.rs
This removes a lot of duplicated code in the property test runner.
There was a lot of copy-pasting happening in the property tests, which led to some friction in adding new test, and some error messages referenced the wrong names, easy to overlook errors when copy pasting.
=> test: Clean up and de-duplicate the property test runners

.github/workflows/ci.yaml, clar2wasm/tests/standard/property_tests.rs, clar2wasm/tests/standard/utils.rs, tests/tests/lib_tests.rs
Reviewing another PR, I noticed that the clippy task in CI does not check tests and benches files.
This PR adds this functionality and fixes now existing warnings.
=> ci: add clippy checks in tests and benches

.github/workflows/ci.yaml
Oh no, it seems there is an issue with actions/checkout@v3 !
Fortunately, v4 just came out and does not suffer the issue.
=> ci: update checkout action to v4

clar2wasm/src/standard/standard.wat, clar2wasm/tests/standard/unit_tests.rs
Fixes #74 
This new implementation is a bit harder to understand.
We now have a `mul-int128`, which does the uint multiplication without overflow checking.
This implementation is a bit hard to understand, but I believe the comments help. Please ping me if it doesn't.
The overflow check is in mul-uint, and uses the sum of the operands leading zeros to check for overflows.
This should be fast since the most usual cases are checked first. For the "bad case", the implementation is a bit long, but those are easy operations (mul-int128, add-uint and bitwise operations).
I modified mul-int while I was at it to use less variables, and make its style closer to the rest of the standard implementation.
To check that this implementation actually fixes the bug, we have to do the check manually for …
=> Fix implementation of mul-uint

clar2wasm/src/standard/standard.wat
Well, *wat2wasm* has a more restrictive parser than Wasmtime I guess.
Adding parentheses did the trick.
=> Fix: standard.wat did compile with wasmtime but not wat2wasm

.github/workflows/ci.yaml, .vscode/settings.json, Cargo.lock, Cargo.toml
Figured out how to avoid those problems with the `stacks-blockchain` directory at the top-level!
=> fix: exclude stacks-blockchain from workspace

clar2wasm/src/standard/standard.wat, clar2wasm/tests/standard/property_tests.rs, clar2wasm/tests/standard/unit_tests.rs, clar2wasm/tests/standard/utils.rs
Fixes #54 
Now we have a huge load of tests, on all kind of ranges of integers, in all configurations.
Good thing, most stuffs work.
Bad thing, the multiplication doesn't.
UPDATE: 
Finally everything works:
- mul-uint had a stupid mistake in the case where the sum of leading zeros was 127 and b is odd
- mul-int overflow detection didn't work. The new algorithm does.
- there was a mistake in the proptests of sqrti-int.
=> Increase the quantity of property tests

clar2wasm/src/standard/standard.wat, clar2wasm/src/wasm_generator.rs, clar2wasm/tests/standard/property_tests.rs, clar2wasm/tests/standard/unit_tests.rs, clar2wasm/tests/standard/utils.rs, tests/contracts/power.clar, tests/tests/lib_tests.rs
This is part of #69 
This PR implements the `pow` function for uint and int types.
~DRAFT: It still needs modifications of `wasm_generator` and "clar-file" tests.~
UPDATE: done.
=> Standard: implementation of pow

.gitignore, clar2wasm/benches/benchmark.rs, clar2wasm/src/standard/standard.wat, clar2wasm/src/wasm_generator.rs, clar2wasm/tests/standard/utils.rs, tests/contracts/get-block-info.clar, tests/tests/lib_tests.rs
This PR follows up on #107. After that is merged, we can set `main` as the target for this one.
This PR adds support for `get-block-info?`. This can't be properly tested yet, because that expression only works on past blocks, and we aren't able to advance the block in our test framework currently. I opened #108 for this.
This expression is included in issue #64.
=> feat: add support for `get-block-info?`

clar2wasm/src/standard/standard.wat, clar2wasm/tests/standard/property_tests.rs, clar2wasm/tests/standard/unit_tests.rs, clar2wasm/tests/standard/utils.rs
This PR adds tests for the Wasm functions `sha256-buf`, `sha256-int`, `hash160-buf` and `hash160-int`.
It introduces a new "Property Struct": `PropBuffer`, to make it easy to generate buffers up to a maximum size and to deal with writing to and reading from memory.
It also adds generic property tests functions for testing hash functions. We should be able to reuse them for `sha512` or `keccak`.
Adding the property tests for those functions, I noticed a of-by-one error in my `sha256-buf` algorithm, in the `extend-data` part. This error is fixed, and a unit test added for this edge case.
This PR solves the buffer part of #125.
=> Property tests for sha256 and hash160

clar2wasm/src/standard/standard.wat, clar2wasm/src/words/buff_to_integer.rs, clar2wasm/src/words/mod.rs, clar2wasm/tests/standard/property_tests.rs, clar2wasm/tests/standard/unit_tests.rs, clar2wasm/tests/standard/utils.rs, tests/contracts/buffer-to-integer.clar, tests/src/lib_tests.rs
Adds the implementation for the buffer functions defined in #65.
There is a little "safety concern" for the `buff-to-x-be`, where I read from memory an offset that is before the one passed as an argument. However, since the standard has data in memory, this offset should never start at 0, and the implementation is safe for our use case.
=> Implement buffer functions

clar2wasm/src/standard/standard.wat, clar2wasm/src/words/comparison.rs, clar2wasm/tests/standard/property_tests.rs, clar2wasm/tests/standard/unit_tests.rs, clar2wasm/tests/standard/utils.rs, tests/contracts/cmp-buffer.clar, tests/src/lib_tests.rs
This PR adds the comparison operators for `buff` and `string-ascii`.
This is part of #118, leaving this issue with the implementation for `string-utf8`.
=> Add comparison operators for buffers and ascii strings

clar2wasm/src/standard/standard.wat, clar2wasm/src/words/mod.rs, clar2wasm/src/words/noop.rs, tests/contracts/noop.clar, tests/src/lib_tests.rs
Noop functions implementation:
`to-int`
`to-uint`
`contract-of`
Related issue: https://github.com/stacks-network/clarity-wasm/issues/144
=> Noop functions implementation

clar2wasm/src/standard/standard.wat, clar2wasm/src/words/equal.rs, clar2wasm/tests/standard/property_tests.rs, clar2wasm/tests/standard/unit_tests.rs, clar2wasm/tests/standard/utils.rs, tests/contracts/equal.clar, tests/src/lib_tests.rs
We had an implementation of `is-eq` for int types. This PR adds nearly all the remaining types (this implementation still lacks equality for `string-utf8` due to #127, and `ListUnionType` and `TraitReferenceType` due to my lack of knowledge about them).
This PR is "quite big". I tried to document as much as possible my code, but there might still be parts that don't make total sense. Please tell me if everything is understandable.
I am really sorry about the size of this PR. It went out of control when I realized that the types of the operands in a `is-eq` expression could be different, depending on the appearance or not of the infamous `NoType`. At that moment, a simple algorithm that just needed to check equality recursively had to become much more complex, and the number of rewrites …
=> Add is-eq implementation for nearly all types

clar2wasm/src/standard/standard.wat, clar2wasm/src/words/conversion.rs, clar2wasm/src/words/mod.rs, clar2wasm/tests/standard/unit_tests.rs
Here is the implementation of `int-to-ascii`.
This is part of #145.
I decided to call the Wasm stdlib function `(u)int-to-string`, since we will certainly reuse it in some way for `int-to-utf8` later.
=> Add int-to-ascii implementation

clar2wasm/src/standard/standard.wat
Issue: https://github.com/stacks-network/clarity-wasm/issues/169
This PR has the intention to raise a discussion about the WAT code organization.
The type section is an optional part of the WebAssembly module definition where the types of functions are declared. These types are essentially templates or blueprints for the signatures of functions used within the module.
Thus, **to simplify the code base**, this section can be removed. And also the type reference in the function, without any penalty in performance or execution.
Would make sense to use type definitions, for better reusability, if we were following one of the code standards below: 
- only indexed params
- named params without the result type
```
(type $funcType (func (param i32 i32) (result i32)))
;; indexed params
(func $add …
```
=> Types definition usage reorg

clar2wasm/src/words/mod.rs
By adding a print in one of these tests to exercise the `Debug` implementations for all of the words, this should also improve code coverage.
=> test: add check for duplicate or invalid `Word`s

clar2wasm/src/wasm_generator.rs, clar2wasm/src/words/consensus_buff.rs, clar2wasm/src/words/mod.rs
This is part of #149.
This PR adds `to-consensus-buff?` support. It was fairly easy since the serialization functions already existed.
Due to a mistake on my side, I ended up refactoring `wasmGenerator::serialize_list`.
This refactor brings several benefits:
- No more useless computations (including a division) for an empty list
- No more useless block around the loop
- One less local
- We have two less jmp instructions at the end of the loop
- Less instructions in the loop
Seeing that this refactoring had those benefits, I decided to keep it, even if it does not bring any new feature.
=> add to-consensus-buff?

clar2wasm/src/bin/main.rs, clar2wasm/src/lib.rs
Expose to things I was needing in clarinet:
- Re-export `walrus::Module`
- Export ast in `CompileResult` and `CompileErr`
New `compile` output signature
=> feat: return ast in compile

Cargo.lock
cargo.lock update.
Will fix stacks-core branch feat/clarity-wasm-next
=> fix: update clarity version in cargo lock

clar2wasm/src/wasm_generator.rs, clar2wasm/src/words/sequences.rs
This solves the problem in #188 in addition to adding support for `string-ascii` and `buff` types.
=> Handle `string-ascii` and `buff` in `fold`

clar2wasm/src/standard/standard.wat, clar2wasm/src/wasm_generator.rs, clar2wasm/src/words/hashing.rs, clar2wasm/tests/standard/property_tests.rs, clar2wasm/tests/standard/unit_tests.rs
This PR adds SHA-512 support in `standard.wat`. 
- `END_OF_STANDARD_DATA` in `wasm_generator.rs` updated to 1352.
- This SHA-512 uses 8 bytes for length (which is sufficient for our use case)
- Written in only one function (for improved performance)
- Existing `sha256-buf` structure followed for consistency 
- Unit tests are passing
=> sha512-buf implementation in standard.wat and unit tests are added

clar2wasm/src/wasm_generator.rs, clar2wasm/src/words/conditionals.rs, clar2wasm/src/words/control_flow.rs
In several scenarios, the type-checker fails to set a complete type for a `response` expression. This type needs to be correct when, for example, returning from a function. If there is a `NoType` for either the `ok` or the `err` portion of the value, the return value will be invalid.
=> fix: failures of type-checker propagating response types

clar2wasm/src/wasm_generator.rs, clar2wasm/src/words/enums.rs, clar2wasm/src/words/equal.rs, clar2wasm/src/words/sequences.rs, clar2wasm/src/words/tuples.rs, clar2wasm/tests/wasm-generation/main.rs, clar2wasm/tests/wasm-generation/regression.rs, clar2wasm/tests/wasm-generation/values.rs, tests/contracts/equal.clar, tests/src/lib_tests.rs
This PR adds a new way to add tests to the codebase. 
We have now in _clar2wasm/tests/wasm-generation_ `prop_signature` which allows the generation of random value signatures, and the struct `PropValue`, which allows the generation of values of any type, or for a determined type.
There is also the first property test that uses them. It checks that any generated value, when evaluated, is equal to itself.
This PR also adds implementations for most of the remaining types in `WasmGenerator::write_to_memory`, since this is needed for `list` values.
It also contains fixes in the `tuple` and `list` functions. The typechecker does not always give the correct type to the values there, which might generate incorrect Wasm code. See the comments in those functions `traverse` for examples.
There is …
=> Property tests for generated values

clar2wasm/src/words/equal.rs, clar2wasm/src/words/sequences.rs
Add support for String::ASCII and Buff on `index-of` function.
Edit: and also support for String::UTF-8.
=> support for ascii, buff and utf-8 in index-of function

clar2wasm/src/standard/standard.wat, clar2wasm/src/wasm_generator.rs, clar2wasm/src/words/arithmetic.rs, clar2wasm/src/words/conditionals.rs, clar2wasm/src/words/control_flow.rs, clar2wasm/src/words/equal.rs
When an error is thrown from a top-level function, it should trigger a runtime error, known as a `ShortReturn`.
=> Handle thrown errors from top-level statements

clar2wasm/src/standard/standard.wat, clar2wasm/tests/standard/unit_tests.rs
Fixes #142 
I added an `if` statement in the Wasm standard for the only case of overflow in integer division and a unit test to make sure it's triggered.
=> fix(clar2wasm): int division should overflow if i128::MIN / -1

clar2wasm/src/standard/standard.wat, clar2wasm/src/words/conversion.rs, clar2wasm/tests/standard/unit_tests.rs
This PR adds support for UTF8 in `string-to-int?` and `string-to-uint?`.
=> Add support for utf8 for `string-to-(u)int?`

clar2wasm/Cargo.toml, clar2wasm/src/wasm_generator.rs, clar2wasm/src/words/conditionals.rs, clar2wasm/src/words/consensus_buff.rs, clar2wasm/src/words/mod.rs, clar2wasm/src/words/sequences.rs
This completes the implementation of `map`. Once #216 is merged, we can rebase on top of that and uncomment the utf8 part of the test `test_map_mixed`.
=> Implement `map`

README.md
Show off the over 90% test code coverage in a readme badge
=> docs: include codecov badge in readme

clar2wasm/src/words/equal.rs, clar2wasm/tests/wasm-generation/equal.rs, clar2wasm/tests/wasm-generation/regression.rs
Fixes #234 
This bug came from my poor usage of a `i32.or`, where I considered it as if it was a lazy operator.
Replacing it with a if-else statement did the trick.
=> Fix: `is-eq` for optional had a lazy bug

README.md, clar2wasm/Cargo.toml, tests/Cargo.toml
This technique allows us to keep the Git paths in the Cargo.toml files but use the local relative paths for development. The change to the config file can't actually be checked in, because that would then become the default build setting.
=> docs: document how to use `[patch]` for development

clar2wasm/src/wasm_generator.rs, clar2wasm/src/words/conditionals.rs, clar2wasm/src/words/mod.rs, clar2wasm/src/words/sequences.rs
This implements the missing functionality for map
* builtin map of strings
* `and` and `or` as simple words for use in mapping
=> feat: fully functional map/fold

clar2wasm/src/words/default_to.rs, clar2wasm/tests/wasm-generation/default_to.rs, clar2wasm/tests/wasm-generation/main.rs, clar2wasm/tests/wasm-generation/regression.rs
This PR adds two property tests for the `default-to` function:
- `default-to <something> none === <something>`
- `default-to <anything> (some <something>) === <something>`
Adding those tests showed a bug in the current implementation: the typechecker failing to set the complete type for the default and the optional value, there was a small workaround to add a few zeros in the generated Wasm. It didn't work for all cases.
The new fix explicitly fixes the types of both arguments, fixing the issue.
Fixes #232
=> Property tests for `default-to` + fix

clar2wasm/src/standard/standard.wat, clar2wasm/src/words/consensus_buff.rs
Fix missing zero-length buffer handling for utf8 in `from-consensus-buff`
=> fix: zero length utf8 bytes in `from-consensus-buff`

clar2wasm/src/lib.rs, clar2wasm/src/serialize.rs, clar2wasm/src/wasm_generator.rs, clar2wasm/src/words/arithmetic.rs, clar2wasm/src/words/bindings.rs, clar2wasm/src/words/bitwise.rs, clar2wasm/src/words/blockinfo.rs, clar2wasm/src/words/buff_to_integer.rs, clar2wasm/src/words/comparison.rs, clar2wasm/src/words/conditionals.rs, clar2wasm/src/words/consensus_buff.rs, clar2wasm/src/words/constants.rs, clar2wasm/src/words/contract.rs, clar2wasm/src/words/control_flow.rs, clar2wasm/src/words/conversion.rs, clar2wasm/src/words/data_vars.rs, clar2wasm/src/words/default_to.rs, clar2wasm/src/words/equal.rs, clar2wasm/src/words/hashing.rs, clar2wasm/src/words/maps.rs, clar2wasm/src/words/options.rs, clar2wasm/src/words/print.rs, clar2wasm/src/words/responses.rs, clar2wasm/src/words/secp256k1.rs, clar2wasm/src/words/sequences.rs, clar2wasm/src/words/tokens.rs, clar2wasm/src/words/traits.rs, clar2wasm/src/words/tuples.rs
This PR replaces panics with proper error handling and propagation. Some of the `datastore.rs` methods are left because they're only being used in `TestEnvironment`
=> Replace panics with proper error handling in clar2wasm

clar2wasm/tests/wasm-generation/default_to.rs, clar2wasm/tests/wasm-generation/equal.rs, clar2wasm/tests/wasm-generation/main.rs, clar2wasm/tests/wasm-generation/optional.rs, clar2wasm/tests/wasm-generation/regression.rs, clar2wasm/tests/wasm-generation/response.rs, clar2wasm/tests/wasm-generation/values.rs
`check_against_interpreter()` added for property testing. Interpreter and WASM results will be compared, then expected result will be compared.
fixes #243
=> Property test framework improvement: testing against the interpreter

clar2wasm/src/tools.rs, clar2wasm/src/wasm_generator.rs, clar2wasm/src/words/bindings.rs, clar2wasm/src/words/conditionals.rs
This adds checks for binding names not colliding with builtins or user defined functions, mirroring the behavior of the interpreter.
=> Name collisions

clar2wasm/tests/wasm-generation/main.rs
The raw `PropValue` display after a failed test was unpractical and difficult to read.
This PR improves the display by printing a Clarity compatible value and its type.
=> Improve PropValue formatting

Cargo.lock, clar2wasm/src/words/data_vars.rs, clar2wasm/tests/wasm-generation/values.rs
Fixes #249 
This PR adds a property test that check that if a we define a `data-var` to a value and read it right after, the result should be the same value.
This showed several bugs, mostly in the way we read/write values to the Wasm memory.
~~DRAFT PR: it depends on https://github.com/stacks-network/stacks-core/pull/4259~~
~~UPDATE: I found another bug, this is going back to draft~~
=> Property test for `define-data-var`/`get-var` + fixes

.cargo/config, README.md
Simple docs change to help with using local paths instead of git branches for stacks-core dependencies.
=> Fix README and add commented patch in .cargo/config

clar2wasm/src/wasm_generator.rs, clar2wasm/src/words/conditionals.rs, clar2wasm/src/words/equal.rs, clar2wasm/src/words/sequences.rs
Support filtering over buffers.
This also de-duplicates quite a bit of code.
fixes #270
=> Unify list element type extraction, support filtering of buffers

clar2wasm/src/wasm_generator.rs, clar2wasm/src/words/constants.rs, clar2wasm/tests/wasm-generation/values.rs
This PR adds a property test for `define-constant`, which states that a defined constant should be equal to itself, and adds fixes.
One of the fix was a classic: evaluating the argument too late in the traverse function. The other was more subtle: when getting a constant, we can push the offset and length for all in-memory types, except for lists that needs to be dereferenced. I guess the way we write data to memory could be fixed later to remove this exception.
Fixes #205.
This PR also add tests in _words/constants.rs_ to check that issue 205 is correctly fixed.
Thanks @csgui for writing them.
=> Add a property test for `define-constant` and getting one

clar2wasm/src/deserialize.rs, clar2wasm/src/serialize.rs, clar2wasm/src/wasm_generator.rs, clar2wasm/src/words/blockinfo.rs, clar2wasm/src/words/conditionals.rs, clar2wasm/src/words/constants.rs, clar2wasm/src/words/contract.rs, clar2wasm/src/words/data_vars.rs, clar2wasm/src/words/equal.rs, clar2wasm/src/words/hashing.rs, clar2wasm/src/words/maps.rs, clar2wasm/src/words/secp256k1.rs, clar2wasm/src/words/sequences.rs, clar2wasm/src/words/tokens.rs
So far I removed the one in `write_to_memory`. I will remove the rest of the uses in this PR as well.
=> Remove uses of `unimplemented`

Cargo.lock, clar2wasm/src/wasm_generator.rs, clar2wasm/src/words/data_vars.rs, clar2wasm/tests/wasm-generation/main.rs, clar2wasm/tests/wasm-generation/values.rs
This PR adds a property test for `var-set`: a data-var defined to a value then set to another value should be equal to this another value.
It showed two issues with this function:
1. just like `define-data-var`, it needs to dereference the value to read if it is an in-memory type
2. a typechecker issue, where we need to set the type of this value to the one set at the variable definition.
=> Proptest for `var-set` + fixes

clar2wasm/src/tools.rs, clar2wasm/src/words/tuples.rs
This allows the argument to get to be an optional tuple.
The fix is very simple, and might warrant some explanation, it was not clear to me at first that this should work.
The Optional is stored on the stack as `[ discriminant , value/placeholder ]`
Since the logic of getting  data works on the top level, it makes no difference if there is a discriminant underneath it. And since the placeholder is needed in the return value, copying it from the full tuple placeholder solves this problem.
=> feat: Accept optional as argument to `get`

clar2wasm/Cargo.toml, clar2wasm/src/bin/crosscheck.rs
`crosscheck` takes the path to a clarity file as an argument and runs crosscheck, which evaluates the clarity code in both the interpreter and the Clarity-Wasm runtimes and compares the result. This will be used by @moodmosaic for the fuzz testing.
=> feat: add `crosscheck` binary

clar2wasm/src/words/conditionals.rs, clar2wasm/tests/wasm-generation/conditionals.rs
This PR adds property tests for `match`.
It showed that this function suffered from the typechecker issue, so workaround was added to fix arguments types.
=> Add property tests for `match`

clar2wasm/src/words/arithmetic.rs
This fixes both #282 and #281 
It does it by first adding all but the first argument, and then subtracting that from the original.
We should make sure to test this with larger values that might overflow to be sure that the behavior is identical.
=> bug: Make subtraction/division work correctly with multiple arguments

clar2wasm/src/words/sequences.rs, clar2wasm/tests/wasm-generation/main.rs, clar2wasm/tests/wasm-generation/sequences.rs
Added a property test for `append`.
This is part of #266
It showed that the function needed the classic "typechecker workaround".
=> Property test for `append`

clar2wasm/src/words/conditionals.rs, clar2wasm/src/words/sequences.rs
Previously, the type from the input of the `try!` was used to decide the type of the placeholder used when throwing, however this is incorrect. It should be the return type of the current function that is used.
=> fix a bug in `try!` and a bug in `fold`

clar2wasm/src/words/sequences.rs, clar2wasm/tests/wasm-generation/main.rs, clar2wasm/tests/wasm-generation/sequences.rs
This PR adds property tests for `as-max-len?`, which is a part of #266.
UPDATE: adds also tests for `concat`, `element-at?`, `len` and `slice`.
There is the typechecker workaround fix for `concat`.
~~To be fair, this was mostly for adding a new method for `PropValue` which allows to generate any kind of sequence. This will be useful for the coming tests of the remaining functions in the linked issue.~~
=> Property test for simple sequence functions

clar2wasm/tests/wasm-generation/sequences.rs
This PR fixes a few oopsies of mine in the sequences crossprop tests:
- I forgot to add the `proptest_config`
- I used an `unreachable!` instead of a `panic!`
- I tried to mitigate the `ValueTooLarge` errors by reducing the maximum number of elements per lists in generated `any_sequences`.
=> Fixes for some oopsies in sequences proptests

Cargo.lock, clar2wasm/Cargo.toml, clar2wasm/src/deserialize.rs, clar2wasm/src/lib.rs, clar2wasm/tests/wasm-generation/main.rs, tests/Cargo.toml
This PR adds the possibility to generate `principal` type for `PropValue`. Accidentally, it can also generate lists with their entry type set to `ListUnionType` when we generate a list of qualified principals.
This PR fixes the usage of principal:
- by fixing the memory issues in https://github.com/stacks-network/stacks-core/pull/4338
- by concretizing all `ListUnionType`s in expressions after the type checking
- by fixing the deserialization process, which pushed the wrong number of bytes to the reference result
Fixes #305 
Fixes #274
=> Add principal generation to `PropValue`

clar2wasm/src/wasm_generator.rs
This PR calculates total number of initial bytes written in WASM module and compare it with END_OF_STANDARD_DATA
Fixes #275
=> Test added to ensure END_OF_STANDARD_DATA is correct

clar2wasm/src/tools.rs, clar2wasm/tests/wasm-generation/bitwise.rs, clar2wasm/tests/wasm-generation/blockinfo.rs, clar2wasm/tests/wasm-generation/main.rs
Initial pull request with some `crossprop` tests:
- bitwise
- blockinfo
I would like to validate the approach in this PR to make it the base for other implementations.
=> Crossprop tests for bitwise and blockinfo

.github/workflows/scheduled.yaml
Adds a CI workflow to run the property testings every 4 hours.
=> add property testing schedule CI

clar2wasm/src/wasm_generator.rs, clar2wasm/tests/wasm-generation/sequences.rs, tests/contracts/bns.clar, tests/src/lib.rs
This fix adds a typechecker workaround for functions arguments during calls.
This issue seems to only manifest itself when the epoch version is smaller than 2.1, but the fix does not make this distinction since 
- it would require a deeper modification where the epoch is set in the `WasmGenerator`;
- it doesn't hurt the newer epoch to re-set the arguments.
There is some "kind-of-new-specific-test" in the _tests_ package, because this package did not have the capability to check for a different version/epoch. I added the *bns* contract there, which is tested via crosscheck and with epoch 2.0.
I also added an unrelated small fix for the crossprop test `sequences::append_value_to_list`, which could often generate values too large. It made my local tests fail, so I fixed it here.
Fixes #340
=> Fix typechecker failure in function arguments for epoch < 2.1

Cargo.lock, clar2wasm/Cargo.toml, clar2wasm/src/wasm_generator.rs, tests/Cargo.toml
This fixes #316. It will grab the last non-none return value from any top-level expressions and return that, even if the last statement in the top-level code has no return value (e.g. ` define-` function).
=> Fix top-level return value

Cargo.lock, clar2wasm/Cargo.toml, tests/Cargo.toml
I updated the "time" dependency on the stacks-core branch, and need this update to be cascaded to the repo.
This should probably be merged after #350 how is also update the clarity dependency to the previous commit
Note: I updated "time" to > 0.3 because it removes the dependency to "stdweb" which is unmaintained and prevents clarinet from using recent wasm-bindgen versions
=> chore: update clarity

clar2wasm/src/lib.rs, clar2wasm/src/words/functions.rs
Fixes #364 
This fix adds a concretization pass for functions to the `ContractAnalysis` type after the type checking pass in `compile`.
The functions added in the new module _utils_ could have been methods on `ContractAnalysis` and `FunctionType`, but since we only need those for clarity-wasm, I preferred to write them here.
=> Fix: functions return types fail for lists of principal

clar2wasm/src/standard/standard.wat, clar2wasm/tests/standard/unit_tests.rs
Fixes #356 
`$stdlib.pow-int` omitted to check for the second operand higher part in its overflow check.
=> Fix issue #356

Cargo.lock, clar2wasm/src/wasm_generator.rs, clar2wasm/src/words/maps.rs, clar2wasm/tests/wasm-generation/main.rs, clar2wasm/tests/wasm-generation/maps.rs, clar2wasm/tests/wasm-generation/tuple.rs
This test adds property testing for `define-map`, `map-insert`, `map-set`, `map-get?` and `map-delete`.
It showed a big amount of bugs:
- the linked functions didn't dereference keys and values for in-memory types (in stacks-core)
- the computation of types sized was flawed for lists and buffer (in stacks-core)
- all the functions suffered from the typechecker issue
This PR is part of #261 
Fixes #304 
Fixes #345
~~THIS IS A DRAFT: fixing the size computation broke the `append` function.~~
=> Proptests for the Map type functions

.gitmodules, Cargo.lock, clar2wasm/Cargo.toml, clar2wasm/src/initialize.rs, clar2wasm/src/lib.rs, clar2wasm/src/linker.rs, clar2wasm/src/tools.rs, clar2wasm/src/wasm_generator.rs, clar2wasm/src/wasm_utils.rs, clar2wasm/tests/wasm-generation/sequences.rs, tests/Cargo.toml, tests/src/lib_tests.rs
This PR moves most code related to wasm to the clar2wasm repo.
It seems like where the code should be in the first place, and will make developing changes and tests much less painful.
Draft for now since i need to update the paths to use branches instead of hard-coded paths. This was done to make sure the stacks-core side is still working. A pr in that repo removing the code is coming as well soon.
=> Migrate code from stacks-core to clar2wasm

clar2wasm/src/words/tuples.rs, clar2wasm/tests/wasm-generation/tuple.rs
I rewrote the merge traverse function to handle cases such as `(merge {a: 1} {a: "a"})`.
Fixes #359
Fixes #372
=> Fix: cannot merge tuples with same key and value of different type

clar2wasm/src/words/equal.rs
Simple enough fix replacing == on types with a custom comparison
fixes #375
=> fix: Make sure eq works correctly on sequences of different max lengths

clar2wasm/src/words/hashing.rs
It turned out to be a simple fix, slightly obfuscated by the way it was phrased in the code.
I changed the calculations with size_of to just use the numbers, which would have made this error obvious in the first place.
=> fix: upate sizes on traverse_hash

clar2wasm/src/standard/standard.wat, clar2wasm/src/words/consensus_buff.rs
=> fix(clar2wasm): $stdlib.is-valid-string-ascii missed a few chars

clar2wasm/src/standard/standard.wat
PR to remove trailing spaces and blank lines in the `standard.wat` file.
=> remove trailing spaces

clar2wasm/src/linker.rs, clar2wasm/tests/wasm-generation/main.rs, clar2wasm/tests/wasm-generation/tokens.rs
Here are the property tests for the nft functions `define-non-fungible-token`, `nft-burn?`, `nft-mint?` and `nft-get-owner?`.
All of them suffered from a known bug in linked host functions: an "any-type" argument should check if it is an in-memory type and dereference it if it is the case.
=> Property tests for nft functions

.github/workflows/ci.yaml, clar2wasm/src/words/conditionals.rs, clar2wasm/src/words/functions.rs, clar2wasm/tests/standard/unit_tests.rs, clar2wasm/tests/wasm-generation/sequences.rs
Rust 1.78 added new features that make our CI fail:
1. The new debug assertions in the standard lib made a test about invalid utf8 conversion fail.
2. Apparently we had an unused struct `TypedVar` (@krl could you confirm this?)
3. Clippy added a new lint to use `clone_from` in some condition.
I also added an unrelated `ignore` to a test that fails too often, and opened issue #395 .
=> Fixes for the changes due to Rust 1.78

clar2wasm/src/linker.rs, clar2wasm/src/tools.rs, clar2wasm/tests/wasm-generation/main.rs, clar2wasm/tests/wasm-generation/stx.rs
This PR adds property tests for the functions `stx-burn?`, `stx-get-balance`, `stx-transfer?`, `stx-transfer-memo?`.
To use random amounts in the tests, some adaptations were made to the `TestEnvironment`.
All those functions suffered from a wrong conversion of the amount `(i64, i64) -> u128`.
This PR is part of #261 .
~~__It will currently fail the CI until we merge #396 .__~~ _done_
=> Proptests for stx functions

clar2wasm/src/linker.rs, clar2wasm/tests/wasm-generation/tokens.rs
This add proptests for the ft functions `ft-burn?`, `ft-get-balance`, `ft-get-supply`, `ft-mint?`, `ft-transfer?`.
They suffered the same bug as the functions in #397, with the amount erroneously parsed in the linked functions.
As with #397, I didn't test for the unhappy path [for the same reasons](https://github.com/stacks-network/clarity-wasm/pull/397#issuecomment-2098057481).
This PR is part of #261.
=> Proptests for ft functions

clar2wasm/src/words/tuples.rs
Fixes #393
The `tuple` traverse function now evaluates the fields in the order of definition, store the results in locals and load them in the correct final order.
=> Fix tuples fields evaluation order

clar2wasm/src/tools.rs, clar2wasm/src/wasm_generator.rs, clar2wasm/src/words/bindings.rs, clar2wasm/src/words/constants.rs, clar2wasm/src/words/data_vars.rs, clar2wasm/src/words/functions.rs, clar2wasm/src/words/maps.rs, clar2wasm/src/words/tokens.rs, clar2wasm/src/words/traits.rs
=> Validate define functions

clar2wasm/src/wasm_generator.rs, clar2wasm/src/words/constants.rs, clar2wasm/tests/wasm-generation/constants.rs, clar2wasm/tests/wasm-generation/main.rs
While working on #370, I noticed an incoherence in the definition of constants. An in-memory type could have different representations depending on if its definition is from a literal or not.
This PR fixes the problem.
It also adds property tests for constants definition and retrieval.
=> Fix constants definition

clar2wasm/src/words/sequences.rs, clar2wasm/tests/wasm-generation/sequences.rs
Fixes #412 
The type workaround now sets correctly the type of the list argument.
I added a simple test for it and a property test.
=> Fix `append` to `append` issue

clar2wasm/Cargo.toml
It seems that the _clarity_ dependency needed the _testing_ feature only as a dev-dependency before. This PR fixes the recent build problem by moving it to the regular dependencies.
=> Fix clarity dependency features

clar2wasm/src/words/sequences.rs, clar2wasm/tests/wasm-generation/sequences.rs
Simple fix where we check for strings types and the buffer type if the replacement is empty, and throw a runtime error in this case.
Fixes #418
Since I touched this function whose crosscheck test was ignored, I fixed its problem too. It seems it was due to [a typechecker error](https://github.com/stacks-network/stacks-core/issues/4622) which could be _workarounded_ by setting the types of the arguments.
Fixes #395 
(Seems like that issue was poorly assessed: I didn't have any `ValueTooLarge` after the fix, and I ran thousands of examples)
=> Fixes `replace-at?` with empty replacement

clar2wasm/tests/wasm-generation/sequences.rs
I noticed this test was ignored with no reason given, and since it passes it makes sense to just re-enable so that we don't forget
=> test: don't ignore concat_crosscheck

.cargo/config, Cargo.lock, clar2wasm/Cargo.toml, clar2wasm/src/datastore.rs
Update the stacks-core dependencies.
Requiring an upgrade of rusqlite dependency
=> chore: upgrade rusqlite and stacks-core dependencies

clar2wasm/src/deserialize.rs, clar2wasm/src/standard/standard.wat, clar2wasm/src/wasm_generator.rs, clar2wasm/tests/standard/unit_tests.rs
This is the first part of completing #307 .
This PR rewrites completely the tuple deserialization function to allow for the missing functionalities.
For now, the missing functionalities implemented are
- fields can arrive in any order (not just lexicographic order)
- fields cannot be duplicated
To satisfy those conditions, the new algorithm in pseudo-code became
```
let bitset = Bitset::new();
for key in serialized_bytes {
let n = find_index(key)
switch n {
case 1:
if bitset.contains(key) { return None; }
handle_parsing_of_value_1;
bitset.insert(key);
break;
case 2:
if bitset.contains(key) { return None; }
handle_parsing_of_value_2;
bitset.insert(key);
break;
...
default:
check_valid_skippable_key();
check_valid_skippable_value();
break;
}
}
if bitset.full() { return Some(result) } else { …
```
=> Rewrite of tuple consensus-buff deserialization

clar2wasm/benches/benchmark.rs, clar2wasm/src/datastore.rs, clar2wasm/src/wasm_utils.rs, clar2wasm/tests/lib_tests.rs
Title says everything.
Two annoying fixes to add:
- docstrings need better indentation
- a new lint that seems to creates false positive: https://rust-lang.github.io/rust-clippy/master/index.html#/needless_borrows_for_generic_args
=> Chore: fix clippy after 1.80 update

Cargo.lock, clar2wasm/Cargo.toml
Update clarity and stacks-common following this PR https://github.com/stacks-network/stacks-core/pull/5010 (to be merged first)
WIP
- temporarily targeting `refactor/use-relative-path-for-workspace-dependencies` until it's merged
=> chore: update stacks-core dependencies

clar2wasm/src/linker.rs, clar2wasm/src/tools.rs, clar2wasm/src/wasm_utils.rs, clar2wasm/src/words/contract.rs, clar2wasm/tests/wasm-generation/contracts.rs, clar2wasm/tests/wasm-generation/main.rs
This PR adds three property tests for the `contract-call?` function:
1. the first one checks that it can take as many random arguments as it wants and returns a random value
2. the second one checks that it can take a random argument and return it
3. the third one checks that it can take as many random arguments as it wants and use them all
I needed to create a new type of "crosscheck" for those tests. We now have a `crosscheck-multi-contract`, which takes multiple `(contract_name, snippet)` as arguments and executes them in order.
For now, the comparison with the interpreter is disabled because the function that executes it doesn't save interpreted contracts.
There are a few fixes for the issues that the new proptests found.
=> Property tests for `contract-call?`

clar2wasm/src/tools.rs
The new `crosscheck_multi_contract` didn't compare the compiled result with the interpreted one because it lacked a functionality in the `interpret_contract_with_snippet` function.
This is now fixed.
=> Add interpreter comparison in `crosscheck_multi_contract`

Cargo.lock, clar2wasm/src/deserialize.rs, clar2wasm/src/linker.rs, clar2wasm/src/standard/standard.wat, clar2wasm/src/words/consensus_buff.rs, clar2wasm/tests/standard/property_tests.rs, clar2wasm/tests/standard/unit_tests.rs
Closes #307
This PR adds the deserialization of tuples which contains more fields than the result type.
It defines several new standard lib functions:
- one to check that a clarity name is valid
- several to skip a value of any type in memory
- the one for list is a host function because it is way to difficult to validate the type in WAT (see https://github.com/stacks-network/clarity-wasm/issues/307#issuecomment-2064512654)
I had to come with a light workaround for the new table in the standard. It seems that our current version of _wasmtime_ doesn't support multiple tables yet, so I just have a single table with a shift of 5 for the _skip_ functions.
For now, we have only basic unit tests for the new features. I intend to add proptests in a following PR.
~~**DRAFT**: we need …
=> Tuple deserialization: allow extra fields

clar2wasm/src/linker.rs, clar2wasm/src/words/secp256k1.rs
Fixes https://github.com/stacks-network/clarity-wasm/issues/414
The clarity-vm has an additional check for returning `err(2)`:
https://github.com/stacks-network/stacks-core/blob/47db1d0a8bf70eda1c93cb3e0731bdf5595f7baa/clarity/src/vm/functions/crypto.rs#L164
I've kept the test from the issue, but it's redundant wrt the second test and can be removed.
=> Fix secp256k1-recover error condition

clar2wasm/tests/contracts/as-contract.clar, clar2wasm/tests/lib_tests.rs, clar2wasm/tests/wasm-generation/contracts.rs
Closes #287 
Not a lot of testing needed for `as-contract`:
- one to make sure that its scope doesn't leak
- a proptest to make sure it can return any value.
=> Proptest for `as-contract`

clar2wasm/tests/wasm-generation/hashing.rs, clar2wasm/tests/wasm-generation/main.rs
Address the easy ones from https://github.com/stacks-network/clarity-wasm/issues/256.
As suggested by the comment, generates `buff|uint|int` values and crosschecks them. I've used the same `300` as upper bound as the one used in [`standard/property_tests.rs`](https://github.com/stacks-network/clarity-wasm/blob/main/clar2wasm/tests/standard/property_tests.rs#L524). Using the "real" upperbound of `1_048_576` causes OOM (~I guess it's related to https://github.com/stacks-network/clarity-wasm/issues/450,~ opened https://github.com/stacks-network/clarity-wasm/issues/471 to track it).
<details><summary>Failing tests (OOM)</summary>
<p>
```rust
#[test]
fn test_big_buff() {
let mut expected = [0u8; 32];
hex::decode_to_slice(
"c4145364a3ba46002fb14242872f795535bae6738b1e47ba21eb405cfdf820a5",
&mut …
```
=> Proptest for hashing

clar2wasm/tests/wasm-generation/main.rs, clar2wasm/tests/wasm-generation/secp256k1.rs
Property testing for `secp256k1-recover` (https://github.com/stacks-network/clarity-wasm/issues/256):
- Random buffers of correct size
- Random buffers with valid recovery id
- Random buffers with small signature for recovery id 2,3
=> Proptest for `secp256k1-recover`

clar2wasm/tests/wasm-generation/functions.rs, clar2wasm/tests/wasm-generation/main.rs
This PR adds some basic proptests for `define-(public|private|read-only)` (https://github.com/stacks-network/clarity-wasm/issues/289).
There are 4 tests repeated for the three functions (with small variations):
- Define a fn accepting random args, returns another random value
- Define a fn accepting random args, returns one of the args
- Define a fn accepting random args, returns a tuple using all the args
- Define a fn accepting random args, do a `var-set` and return a random response (excluding `define-read-only`)
While writing this I encountered two issues (https://github.com/stacks-network/clarity-wasm/issues/473, https://github.com/stacks-network/clarity-wasm/issues/475) that could inspire some more proptests (random fn/arg names, adding more ops in the fn body to ~mess~ interact …
=> Proptest for define functions

clar2wasm/src/linker.rs, clar2wasm/src/words/secp256k1.rs, clar2wasm/tests/wasm-generation/secp256k1.rs
This PR adds proptests for `secp256k1-verify` (closes https://github.com/stacks-network/clarity-wasm/issues/256):
- Random values matching the expected types;
- Random values with correct signature (both with, without and with a different valid recovery id;
- Random values with correct signature but random (potentially non valid) recovery id;
It also includes a fix for the function (and relevant test) as it was missing the check on the recovery id present on clarity vm.
=> Proptest for secp256k1-verify

clar2wasm/src/tools.rs, clar2wasm/tests/wasm-generation/arithmetic.rs
Compare only crosscheck can easily let certain errors slide through, if they affect both sides.
We should only allow compare_only to compare successful test results.
=> disallow failures in compare_only

clar2wasm/src/wasm_generator.rs, clar2wasm/src/words/constants.rs, clar2wasm/tests/wasm-generation/constants.rs
Fixes https://github.com/stacks-network/clarity-wasm/issues/450.
When loading a constant, allocate stack space for it.
Note that, as `frame_size` is never reclaimed, loading consts multiple times will make the stack grow for each call, even if they are not used at the same time.
=> Allocate stack space when loading constants

clar2wasm/src/wasm_generator.rs, clar2wasm/src/words/bindings.rs, clar2wasm/src/words/conditionals.rs, clar2wasm/src/words/contract.rs, clar2wasm/tests/wasm-generation/contracts.rs
Fixes #481 
This PR adds a new `Binding` struct used in `WasmGenerator`, so that bindings now remember the trait if needed.
=> Fix: `contract-call?` with trait name in a `let` or `match` binding

clar2wasm/src/serialize.rs, clar2wasm/src/words/print.rs, clar2wasm/tests/wasm-generation/main.rs, clar2wasm/tests/wasm-generation/print.rs
Fixes https://github.com/stacks-network/clarity-wasm/issues/407.
Allocate some work space for the serialized print. We need to replace the `NoType`s in the type signature in order to get its `max_serialized_size`.
=> Reserve work space for print serialized value

clar2wasm/tests/wasm-generation/contracts.rs, clar2wasm/tests/wasm-generation/main.rs, clar2wasm/tests/wasm-generation/traits.rs
Closes #264
This implements the remainings testing for the trait functions:
- one that checks that `contract-call?` can use all of its arguments
- one that creates a contract that defines a trait with a random number of methods, each having a random number of args and returning a random value, then a second contract that implements that traits.
~~THIS IS A DRAFT: I based this branch on the work of #483, we need this one merged first.~~
=> Remaining proptests for trait functions

clar2wasm/src/words/print.rs, clar2wasm/src/words/sequences.rs
Fix https://github.com/stacks-network/clarity-wasm/issues/411.
Allocate enough space for the (worst case) output type size.
=> Allocate enough stack space for output in `map`

clar2wasm/src/tools.rs, clar2wasm/src/words/print.rs, clar2wasm/tests/wasm-generation/print.rs
Add a crosscheck variation checking also the emitted events (first step for https://github.com/stacks-network/clarity-wasm/issues/398).
I've added a separate crosscheck for now to avoid overlapping with https://github.com/stacks-network/clarity-wasm/pull/498. 
Once both are merged we can add the events check directly in the usual crosschecks (and remove the variant introduced here), closing https://github.com/stacks-network/clarity-wasm/issues/398.
Events are compared using their serialized representation, as the interpreted clarity can emit arbitrary `Value`s -- eg `CallableType`s -- that may not have a sip5 specific representation -- eg they are coerced to contract principal. See `words::traits::tests::trait_list` for an example of this (in particular, we are talking about the `print` …
=> Add events crosscheck

clar2wasm/src/linker.rs, clar2wasm/src/words/blockinfo.rs
Fixes https://github.com/stacks-network/clarity-wasm/issues/381.
Given that we would not be able to distinguish between a data var containing `none` and a missing one, I used a different approach instead of the workarounds suggested in the issue.
Also note that we cannot crosscheck, since the interpreter is happily returning `none` (despite the [docs making this exact example](https://docs.stacks.co/reference/functions#at-block:~:text=(at%2Dblock%20(get%2Dblock%2Dinfo%3F%20id%2Dheader%2Dhash%200)%20(var%2Dget%20data))) and stating it would throw).
Also changed the test since for v3 we should use `get-stacks-block-info`, but this one is still not implemented.
=> Return runtime error if data var is missing

clar2wasm/src/wasm_utils.rs
Instead of `ast::parse`, which apparently is a [testing-gated legacy function](https://github.com/stacks-network/stacks-core/blob/master/clarity/src/vm/ast/mod.rs#L46-L48), use a better one.
=> Avoid using testing-gated parse function

clar2wasm/src/tools.rs, clar2wasm/src/words/print.rs, clar2wasm/tests/wasm-generation/blockinfo.rs, clar2wasm/tests/wasm-generation/print.rs, clar2wasm/tests/wasm-generation/stx.rs
Address https://github.com/stacks-network/clarity-wasm/issues/398.
Add events comparison to all the crosschecks. To avoid duplication I've done a small refactoring of the `crosscheck*` scaffolding (and removed the now obsolete `crosscheck_with_events`).
During the refactoring I've removed the error remapping logic since (I guess) it wasn't needed anymore, and in doing so an issue with a not version gated `get-block-info?` test surfaced: it was removed in v3, but we don't support the `get-stacks-block-info?` replacement yet.
=> Add events comparison to all the crosschecks

clar2wasm/src/lib.rs, clar2wasm/src/words/constants.rs
Fixes https://github.com/stacks-network/clarity-wasm/issues/452.
Constant types were missing concretization.
=> Concretize constants

clar2wasm/src/tools.rs, clar2wasm/tests/wasm-generation/bitwise.rs, clar2wasm/tests/wasm-generation/blockinfo.rs, clar2wasm/tests/wasm-generation/comparison.rs, clar2wasm/tests/wasm-generation/stx.rs
This add some missing feature gates for clarity v1 tests. For some reason GH messes up the diff for `bitwise.rs`, consider hiding whitespaces for the review.
The v1 tests are still flaky because of `crosscheck_index_of` (https://github.com/stacks-network/clarity-wasm/issues/496, https://github.com/stacks-network/clarity-wasm/issues/503) and `tokens::nft_mint*` (https://github.com/stacks-network/clarity-wasm/issues/515).
=> Add missing clarity v1 feature gate in tests

clar2wasm/src/tools.rs
Lists of principal as arguments of some functions can cause [this bug](https://github.com/stacks-network/stacks-core/issues/4622).
This PR changes the `crosseval` function so that it can detect if this bug happen, and ignore the results comparisons.
There is actually an entire new enum `KnowBugs` so that it's easy to add more detection of bugs if we find some other ones.
It would have been nice to compare the errors from interpreted and compiled, but we need this issue fixed first: #421 
I would have been nice to use a logger instead of the `println` also, or have a counter to check how many times such bugs happen, but I think this is overkill for this PR.
=> Ignore the list of qualified principal in tests

clar2wasm/src/wasm_generator.rs, clar2wasm/src/words/sequences.rs
This PR adds a mechanism to re-use locals, reducing the amount of generated local id's that were getting out of hand.
Only used in one place at the moment, but could be re-used in other places as well when we see the need.
fixes #486
=> Add a `BorrowedLocal` to reduce local bloat

clar2wasm/tests/wasm-generation/consensus_buff.rs, clar2wasm/tests/wasm-generation/main.rs
Closes #487
This PR implements 3 property tests for the deserialization of tuples with extra fields. This indirectly tests the "skip" functions from _standard.wat_.
=> Proptests for the "skip" functions in tuple deserialization

clar2wasm/src/tools.rs
=> Adapt the regex to detect the "list-of-principal" bug to work with Clarity1 too

clar2wasm/src/deserialize.rs, clar2wasm/src/serialize.rs, clar2wasm/src/wasm_generator.rs, clar2wasm/src/wasm_utils.rs, clar2wasm/src/words/equal.rs, clar2wasm/src/words/tuples.rs
Removed the `ordered_tuple_signature` and `owned_ordered_tuple_signature` functions from `wasm_utils.rs`. These functions are now redundant as `TupleTypeSignature` uses a `BTreeMap` internally.
Changes:
- Removed redundant functions from `wasm_utils.rs`
- Updated affected code to use `TupleTypeSignature::get_type_map()` directly
- Adjusted type handling in relevant functions
Resolves #504
=> refactor: Remove redundant tuple signature conversion functions

Cargo.lock, clar2wasm/src/debug_msg.rs, clar2wasm/src/lib.rs, clar2wasm/src/linker.rs, clar2wasm/src/standard/standard.wat, clar2wasm/src/wasm_generator.rs
Used like this example, prints a message to stdout when a given wasm code path is traversed.
```rust
generator.debug_msg(builder, "in wasm_equal");
```
=> Create a method to print debug messages from wasm guest

clar2wasm/src/wasm_generator.rs, clar2wasm/src/words/tokens.rs
Fixes #515 
The problem happens only with Clarity1, the typechecker doesn't set the defined type for the asset identifier, it just interpolates it from the value.
The fix is applied without regards to the version of Clarity, since it doesn't harm the process.
=> Set the correct type for NFT identifiers

clar2wasm/src/error_mapping.rs, clar2wasm/src/initialize.rs, clar2wasm/src/standard/standard.wat, clar2wasm/src/wasm_generator.rs, clar2wasm/src/wasm_utils.rs, clar2wasm/src/words/conditionals.rs, clar2wasm/src/words/print.rs, clar2wasm/tests/wasm-generation/conditionals.rs
fix #385 
This PR implements the follwoing errors handling:
- `ShortReturn::AssertionFailed`
- `ShortReturn::ExpectedValue`
- `ShortReturn::ExpectedValueResponse`
- `ShortReturn::ExpectedValueOptional`
=> fix short-return type value in runtime-errors

clar2wasm/src/lib.rs
The new Rust update 1.82 created this new clippy warning that prevents the CI from passing:
```
error: the `Err`-variant returned from this function is very large
--> clar2wasm/src/lib.rs:63:6
|
49 | /     Generic {
50 | |         ast: ContractAST,
51 | |         diagnostics: Vec<Diagnostic>,
52 | |         cost_tracker: Box<LimitedCostTracker>,
53 | |     },
| |_____- the largest variant contains at least 240 bytes
...
63 |   ) -> Result<CompileResult, CompileError> {
|        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
|
= help: try reducing the size of `CompileError`, for example by boxing large elements or replacing it with `Box<CompileError>`
= help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#result_large_err
= note: `-D clippy::result-large-err` …
```
=> Fix new clippy warning from Rust 1.82

Cargo.lock, clar2wasm/src/datastore.rs
This fix adds `get_stacks_height_for_tenure_height ` present in the `HeadersDB` trait. That was [added](https://github.com/stacks-network/stacks-core/blob/develop/clarity/src/vm/database/clarity_db.rs#L130-L134) in `stacks-core` and need to be replicated to `clarity-wasm`.
Also updates `Cargo.lock`.
=> Fix datastore trait

clar2wasm/src/words/equal.rs
Workaround for index-of
thanks to @Acaccia for the actual solution!
=> Workaround for index-of

clar2wasm/src/tools.rs
Most `crosscheck` functions have more or less the same body, so this commit implements said logic in an `execute_crosscheck` function and makes the `crosscheck` functions call it instead.
Resolves: #524
=> Make all `crosscheck` functions call `execute_crosscheck`

Cargo.lock, clar2wasm/src/initialize.rs, clar2wasm/src/wasm_utils.rs
=> Use `wasmtime::Engine` provided by `GlobalContext`

clar2wasm/src/bin/main.rs
This PR is adding command-line arguments to set the Clarity version and Stacks epoch dynamically when running the compiler. Previously, these values were hardcoded to Clarity2 and Epoch25 in `main.rs` that are now the default versions.
Related issue: #554
=> Add command-line arguments for ClarityVersion and Stacks epoch

.github/workflows/scheduled.yaml, clar2wasm/tests/standard/property_tests.rs
Add a job to notify @stacks-network/clarity-wasm team when property testing has failed.
We can also have a Slack integration as a compliment to the automated issue. To be handled in other PR, if the case.
Issue generated as a test: https://github.com/stacks-network/clarity-wasm/issues/455
=> CI Notify on failure

clar2wasm/tests/wasm-generation/sequences.rs
That was my bad, I unwrapped like a savage.
=> Prevent the genaration of `ValueTooLarge` in `append` proptests

clar2wasm/src/wasm_generator.rs, clar2wasm/tests/wasm-generation/function_calls.rs, clar2wasm/tests/wasm-generation/main.rs
Issue #475 showed that our current handling of returned values after functions calls was incomplete.
Our current handling would copy the returned values for in-memory types, such as lists or strings.
But it completely missed in-memory types inside composed types. So a function that would return an `(optional string)` was not copied and could have its string overwritten.
This PR completes the copying to any possible types. It also adds the testing of the failing example in the issue and a property test that checks if the call of a function doesn't overwrite the result of a previous function.
This fix broke the `print::test_large_serialization` test at first. This is due to a bug in our memory allocation in the `map` function.
To mitigate it, I created a function that computes the amount of …
=> Fix the erasing of functions returned values

clar2wasm/src/words/consensus_buff.rs
This PR addresses the out of bounds memory access bug on `to-consensus-buff?`.
Related issue: #571
=> `to-consensus-buff?` out of bounds memory access fix

.github/workflows/benchmarks.yaml, README.md, clar2wasm/Cargo.toml, readme.html
The benchmarks workflow will run the benchmarks and publishes them on GitHub pages, providing a chart view. It will detect possible performance regressions, posting a comment on the pull request, but will not fail the checks.
Results will be available at https://stacks-network.github.io/clarity-wasm/dev/bench/
=> Add benchmark workflow

clar2wasm/src/words/hashing.rs
This PR addresses a bug where the results of the following expressions were being unintentionally overwritten:
- `(map hash160 (list 1 2 3))`
- `(map sha256 (list 1 2 3))`
- `(map sha512 (list 1 2 3))`
The fix ensures that the outputs are correctly retained without overwriting.
Fixes: #590
=> Fix overwriting of `hash160`, `sha256`, and `sha512` mapping results

clar2wasm/src/words/principal.rs, clar2wasm/tests/oom-checker/unit_tests.rs
This pull request resolves an out-of-bounds memory access issue in the `principal-of?` function.
Fixes: #585
=> Fix OOM on 'principal-of?`

clar2wasm/tests/wasm-generation/maps.rs
Prevent large lists generation for `map-get` and `map-set` proptests.
=> prevent generation of large lists on proptest

clar2wasm/src/standard/standard.wat, clar2wasm/src/words/conversion.rs, clar2wasm/tests/oom-checker/unit_tests.rs, clar2wasm/tests/standard/unit_tests.rs
This PR addresses an out-of-memory access issue occurring in the `int-to-ascii` and `int-to-utf8` functions.
Fixes: #592
=> Fix OOM issue on `int-to-ascii` and `int-to-utf8`

clar2wasm/benches/comparison.rs
To prevent compiler optimization based on contract code, called function, or arguments passed, we use `black_box` to surround these before passing them on to both `interpreter()` and `webassembly()`.
=> bench: use `black_box` in appropriate places

clar2wasm/benches/comparison.rs
The range of values the `add_prices` benchmark is performed under doesn't showcase the important of the behavior that we want to capture very well - meaning the transition from the "interpreter better" to "webassembly better" regimes. This commit improves that by changing this range to a more representative value.
=> benches: improve resolution of `add_prices`

clar2wasm/benches/comparison.rs
This commit adds a benchmark for a contract that is particularly poorly behaved using the interpreter. The original contract has a *much* longer list definition, but since not even the interpreter allows for its execution, we shorten it, varying its length as a parameter.
The WebAssembly runtime seriously outshines the interpreter in the execution of this contract - to the tune of 25x faster.
=> Add poc2 contract to benchmark suite

clar2wasm/src/tools.rs, clar2wasm/src/words/blockinfo.rs
update Test environment default to latest epoch and latest Clarity version
fix #613
=> fix default test environment

clar2wasm/src/linker.rs, clar2wasm/src/tools.rs, clar2wasm/tests/standard/unit_tests.rs, clar2wasm/tests/standard/utils.rs
Fix the new clippy warnings. Most of them were due to the [precedence lint](https://rust-lang.github.io/rust-clippy/master/index.html#precedence).
=> Chore: fix new clippy 1.85 warnings

clar2wasm/benches/comparison.rs, clar2wasm/build.rs, clar2wasm/src/bin/main.rs, clar2wasm/src/cost.rs, clar2wasm/src/cost/clar3.rs, clar2wasm/src/error_mapping.rs, clar2wasm/src/initialize.rs, clar2wasm/src/lib.rs, clar2wasm/src/standard/standard.wat, clar2wasm/src/tools.rs, clar2wasm/src/wasm_generator.rs, clar2wasm/src/wasm_utils.rs, clar2wasm/tests/lib_tests.rs, clar2wasm/tests/oom-checker/main.rs
This commit introduces the scaffold necessary to implement cost-tracking code generation.
The runtime gets access to three new items: the `AccessCostMeter` and `CostLinker` traits, and the `CostMeter` struct, which together allow for setting and retrieving the cost limits when running a module. The runtime also gets a choice of whether to compile Clarity with or without the cost tracking code.
The binaries - `clar2wasm` and `crosscheck` - can now receive a new `--cost-tracking` flag, to optionally generate cost tracking code.
To facilitate further implementation, implementers of `SimpleWord` and `ComplexWord` are extended with the `SimpleWordCharge` and `ComplexWordCharge` traits, respectively. These allow the implementer to simply call `fn charge(n: Scalar)` on the word, to generate the …
=> cost-tracking: scaffold compiler and runtime code

clar2wasm/src/duck_type.rs, clar2wasm/src/lib.rs, clar2wasm/src/linker.rs
This PR adds a `duck-type` function for the purpose of converting a value representation from an original type to a target type.
This will be needed for functions like `filter` which allows code like
```clarity
(define-private (foo (a (response int bool))) (and (is-ok a) (< (unwrap-panic a) 100)))
(define-private (bar (a (response int uint))) (and (is-ok a) (> (unwrap-panic a) 42))) 
(filter bar (filter foo (list (ok 1) (ok 50))))
```
This is the first part of fixing #608.
This will remove any need for a new typechecker as discussed in #488 and #419.
This will allow us to remove the horrible _lib.rs_ `typechecker workaround` and make #492 void.
=> Duck-typing Part I : Origins

clar2wasm/Cargo.toml
The new lint "result_large_err" gave a lot of warnings due to stacks-core error types.
Here is a copy-paste of the comment I wrote on slack about it:
```
Hi people of Clarity-Wasm,
With the new version of Rust come the new clippy warnings. In this case it's massive: they added a check for [LLLLAAARRRGGGGEEEE error variants in `Result`](https://rust-lang.github.io/rust-clippy/master/index.html#result_large_err) and the errors we are pulling from stack-core are all flagged by this lint.
Problem is: we cannot just box the errors and call it a day, since we implement some traits where the methods need to return those large variants.
I propose we just add a flag to ignore this lint and let the people who deal with stacks-core clippyness fix it for us.
The alternative is the create a struct …
```
=> Chore: clippy 1.89

clar2wasm/src/lib.rs, clar2wasm/src/words/sequences.rs
This PR adds duck-typing to the code generation for `fold`.
This PR also definitely removes the need for the infamous "typechecker workaround" in _lib.rs_.
Fixes #649 
Closes #492
=> Duck-typing Part III: Fold

clar2wasm/src/words/sequences.rs
While working on #678 , I noticed the problem didn't come from the implementation of `fold`, but from `append`. 
`append` used the maximum length from the type as the result length instead of using the actual length of the list.
A quick look in the rest of the file and I noticed that `replace-at?` suffered the same issue.
This PR fixes those two functions and adapt the cost tracker with the changes on their algorithms.
Closes #678
=> Fixes for `append` and `replace-at?`

clar2wasm/src/words/blockinfo.rs
This PR adds `vrf-seed` property to the `get-block-info?` function.
fixes: #670 & #687
=> `get-block-info?` missing property `vrf-seed`

clar2wasm/src/words/functions.rs, clar2wasm/tests/contracts/private-call.clar, clar2wasm/tests/lib_tests.rs
Certain special contracts, such as PoX and signer contracts, invoke private functions directly within the contract.
To support these use cases, private functions must also be exported by the WebAssembly module.
=> allow call to some private functions

clar2wasm/src/wasm_generator.rs, clar2wasm/src/words/bindings.rs, clar2wasm/src/words/conditionals.rs, clar2wasm/src/words/control_flow.rs, clar2wasm/tests/wasm-generation/conditionals.rs
This PR reimplements different functions due to the fact that they were generating `if` with different types for the `then` branch and the `else` branch.
The functions reimplemented are `try!`, `asserts!`, `unwrap!` and `unwrap-err!`.
A new enum `ShortReturnable` was added to handle the code generation of all the short-returnable situation.
A big amount of tests were added to the proptests, to make sure that the new implementation would work in all cases. It also showed that we had a need for a typechecker workaround in the unwrapping functions.
Fixes #705 
Fixes #573
=> Reimplementation of `try!`

clar2wasm/src/wasm_generator.rs, clar2wasm/src/words/conditionals.rs, clar2wasm/src/words/sequences.rs
Issue #707 showed that a function return type could be different than the expected type from the caller.
This PR adds an optional parameter to `visit_call_user_defined` which is the type that the caller expects as a result and will be used with duck typing.
This PR had to refactor a bit the algorithm of `fold` to accommodate the changes.
This PR also has a fix for `map` which didn't use the duck-typing yet (+ a test showing its necessity).
And as a bonus, I removed a forgotten `dbg` in the code.
Fixes #707
=> Duck-typing for function calls

clar2wasm/src/wasm_generator.rs, clar2wasm/src/words/functions.rs
This PR adds a `defined_functions` HashSet to prevent false duplicate name errors in `literal_memory`.
The issue was caused by `contract-call?`, which was saving the name of the function it calls into `literal_memory`. As a result, if the contract also defines a function with the same name, the compiler would wrongly throw a `NameAlreadyUsed` error.
Closes: #712
=> FIx `NameAlreadyUsed` bug
