stacks-network/clarity-wasm

.vscode/settings.json
Cargo.lock
README.md
clar2wasm/src/standard/standard.wat
clar2wasm/src/standard/tests.rs
clar2wasm/src/wasm_generator.rs
tests/Cargo.toml
tests/contracts/var-get.clar
tests/contracts/var-set.clar
tests/src/datastore.rs
tests/src/lib.rs
tests/src/util.rs

Forgive me for this code! I will clean it up, but wanted to get something working and shared.

Add support for `define-data-var`, `var-get`, and `var-set`

---

Cargo.lock
Cargo.toml
clar2wasm/Cargo.toml
clar2wasm/src/lib.rs
tests/Cargo.toml
tests/src/lib.rs

I pushed this branch to keep track of the changes I made to integrate it with clarinet.
Using the clarity-vm published crate is important
cc @obycode

feat: clarinet compat

---

.github/workflows/ci.yaml

https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#merge_group

ci: add `merge_group` to support merge queues

---

clar2wasm/src/ast_visitor.rs

Added comment as discussed in #44.

docs: clarify when to use `traverse_*` vs `visit_*`

---

README.md

docs: Replace Hiro ASCII art with Clarity ASCII art

---

clar2wasm/src/lib.rs
clar2wasm/src/wasm_generator.rs
clar2wasm/src/words/arithmetic.rs
clar2wasm/src/words/definitions.rs
clar2wasm/src/words/mod.rs
clar2wasm/src/words/traits.rs

Initial implementation of Word trait

Further reduction of unused code

---

clar2wasm/src/wasm_generator.rs
clar2wasm/src/words/mod.rs
clar2wasm/src/words/tuples.rs
tests/contracts/print.clar
tests/contracts/tuple.clar
tests/src/lib_tests.rs

Adds support for:
- `tuple`
- `get`
- `merge`
- tuple serialization
Closes #68

Add support for tuples

---

clar2wasm/src/standard/standard.wat

Refactor $store-i32-be and $store-i64-be

---

clar2wasm/src/wasm_generator.rs
clar2wasm/src/words/mod.rs
clar2wasm/src/words/responses.rs
tests/contracts/responses.clar
tests/src/lib_tests.rs

PR with implementation of the following functions:
`is-ok`
`is-err`
https://docs.stacks.co/docs/clarity/language-functions#is-ok
https://docs.stacks.co/docs/clarity/language-functions#is-err

is-ok and is-err functions implementation

---

clar2wasm/src/words/mod.rs
clar2wasm/src/words/options.rs
tests/contracts/options.clar
tests/src/lib_tests.rs

PR with implementation of the following functions:
`is-some`
`is-none`

is-some and is-none functions implementation

---

clar2wasm/src/words/default_to.rs
clar2wasm/src/words/mod.rs
tests/contracts/default-to.clar
tests/src/lib_tests.rs

`default-to` function implementation.

default-to implementation

---

.github/workflows/ci.yaml

This is a WIP but I'm not sure how to test it other than opening a PR.

Add code coverage

---

clar2wasm/src/standard/standard.wat
clar2wasm/src/words/conversion.rs
clar2wasm/src/words/mod.rs
clar2wasm/tests/standard/unit_tests.rs

This PR is a part of #145.
It adds the "string-to-int" conversions.
I didn't add property tests for these ones. Maybe call it laziness, but I don't necessarily see the point for such simple functions, and with the unit tests dealing already with the edge cases.

add string-to-uint? and string-to-int?

---

clar2wasm/src/words/conditionals.rs
clar2wasm/src/words/mod.rs

This adds `and` and `or` words.

Add `and` and `or` words

---

clar2wasm/src/tools.rs
clar2wasm/src/wasm_generator.rs
clar2wasm/src/words/bindings.rs
clar2wasm/src/words/conditionals.rs
clar2wasm/src/words/functions.rs
clar2wasm/src/words/mod.rs

Add the match logic for results and optionals.

feat Match word implementation

---

clar2wasm/src/wasm_generator.rs
clar2wasm/src/words/conditionals.rs
clar2wasm/src/words/functions.rs
clar2wasm/src/words/mod.rs

feat: `unwrap!` word

---

clar2wasm/src/words/control_flow.rs

This was accidentally left as a placeholder, but now has a proper implementation.

feat: implement `unwrap-err-panic`

---

Cargo.lock
clar2wasm/Cargo.toml
tests/Cargo.toml

Needed for https://github.com/stacks-network/stacks-core/pull/4119

chore: load clarity vm from github

---

clar2wasm/src/words/equal.rs
clar2wasm/src/words/mod.rs

`index-of?` (or `index-of`) implementation.

index-of? implementation

---

clar2wasm/src/words/conditionals.rs
clar2wasm/src/words/mod.rs

The final control flow function from #62
closes #62

feat: Implement `asserts!`

---

clar2wasm/src/standard/standard.wat
clar2wasm/src/words/conversion.rs
clar2wasm/src/words/mod.rs
clar2wasm/tests/standard/unit_tests.rs

Add `int-to-utf8`

---

clar2wasm/benches/benchmark.rs

Link missing functions to benchmark.

link missing functions

---

clar2wasm/benches/benchmark.rs

This PR contains benchmarks for hashing functions.
1. Clarity
- SHA512 and SHA256
3. Clarity WASM
- SHA512 and SHA256

Benchmarks for hashing functions added

---

clar2wasm/tests/wasm-generation/main.rs
clar2wasm/tests/wasm-generation/optional.rs
clar2wasm/tests/wasm-generation/response.rs

This PR addresses [this](https://github.com/stacks-network/clarity-wasm/issues/244) issue

Property tests for optional and response functions

---

clar2wasm/src/tools.rs
clar2wasm/src/words/arithmetic.rs
clar2wasm/src/words/blockinfo.rs
clar2wasm/src/words/conditionals.rs
clar2wasm/src/words/consensus_buff.rs
clar2wasm/src/words/control_flow.rs
clar2wasm/src/words/conversion.rs
clar2wasm/src/words/equal.rs
clar2wasm/src/words/hashing.rs
clar2wasm/src/words/noop.rs
clar2wasm/src/words/principal.rs
clar2wasm/src/words/secp256k1.rs
clar2wasm/src/words/sequences.rs
clar2wasm/src/words/traits.rs
clar2wasm/tests/wasm-generation/default_to.rs
clar2wasm/tests/wasm-generation/equal.rs
clar2wasm/tests/wasm-generation/optional.rs
clar2wasm/tests/wasm-generation/regression.rs
clar2wasm/tests/wasm-generation/response.rs
clar2wasm/tests/wasm-generation/values.rs

This adds `crosscheck` functionality, which is a convenient way to run tests in both the compiled and interpreted variants.
Some minor issues found, that i will be making into their own separate issues.

Crosscheck

---

clar2wasm/src/tools.rs
clar2wasm/src/words/arithmetic.rs
clar2wasm/src/words/mod.rs
clar2wasm/tests/wasm-generation/arithmetic.rs
clar2wasm/tests/wasm-generation/bindings.rs
clar2wasm/tests/wasm-generation/main.rs

Adds crosscheck property testing for the expressions defined in arithmetic.rs and fixes some simple bugs that were found. This testing also exposed #281 and #282 which are left open to be fixed later.

Test arithmetic expressions

---

clar2wasm/src/words/bindings.rs

This PR fixes a typechecker issue in the `let` expression, found by @hugocaillard with this piece of clarity code:
```
(define-data-var count uint u0)
(define-public (decrement)
(let ((current-count (var-get count)))
(asserts! (> current-count u0) (err u1))
(ok (var-set count (- current-count u1)))
)
)
```

Fix `let` expression typechecker issue

---

clar2wasm/tests/wasm-generation/arithmetic.rs

Fix: functions that expects two operands were receiving only one operand.

arithmetic crossprop test

---

Cargo.lock
clar2wasm/Cargo.toml
tests/Cargo.toml

chore: update dependencies

---

clar2wasm/src/wasm_generator.rs
clar2wasm/src/words/arithmetic.rs
clar2wasm/src/words/mod.rs
clar2wasm/src/words/sequences.rs
clar2wasm/tests/wasm-generation/arithmetic.rs

both when called directly, and when used in map/fold
This is a less invasive, and more correct approach than the now closed #323
fixes #282 and #281

Make sure that variadic calls are executed correctly

---

clar2wasm/tests/wasm-generation/comparison.rs
clar2wasm/tests/wasm-generation/main.rs

Tests for comparison functions checking string-ascii arguments.

crossprop tests for comparison functions

---

Cargo.lock
clar2wasm/Cargo.toml
clar2wasm/benches/benchmark.rs
clar2wasm/src/datastore.rs
clar2wasm/src/lib.rs
clar2wasm/src/tools.rs
clar2wasm/src/words/mod.rs
clar2wasm/tests/wasm-generation/main.rs
clar2wasm/tests/wasm-generation/sequences.rs
tests/Cargo.toml
tests/benches/benchmark.rs
tests/src/lib_tests.rs

This works with the latest updates that merged next into feat/clarity-wasm-next.

chore: fixes to update to latest stacks-core branch

---

clar2wasm/tests/wasm-generation/main.rs
clar2wasm/tests/wasm-generation/noop.rs

crossprop tests for noop functions

---

clar2wasm/tests/wasm-generation/control_flow.rs

This PR adds some property tests for `begin` function.
closes #293

prop-tests for begin function added

---

Cargo.lock
clar2wasm/src/linker.rs
clar2wasm/src/standard/standard.wat
clar2wasm/src/wasm_generator.rs
clar2wasm/src/words/constants.rs
clar2wasm/tests/contracts/constant-expr.clar
clar2wasm/tests/contracts/constant-literal.clar
clar2wasm/tests/lib_tests.rs

fix #370 
Issue with constant expression evaluation inside functions.

Fix issue with constant expression evaluation

---

Cargo.lock
clar2wasm/src/wasm_utils.rs

Addressing TODOs. Same work done into stacks-core repo.

addressing TODOs

---

Cargo.lock
clar2wasm/src/lib.rs
clar2wasm/src/linker.rs
clar2wasm/src/tools.rs
clar2wasm/src/words/conditionals.rs
clar2wasm/src/words/sequences.rs
clar2wasm/tests/wasm-generation/conditionals.rs
clar2wasm/tests/wasm-generation/main.rs
clar2wasm/tests/wasm-generation/regression.rs
clar2wasm/tests/wasm-generation/sequences.rs

Anthonys workaround, de-unwrapped plus a trivial test.

Property testing of fold/filter

---

clar2wasm/tests/wasm-generation/main.rs
clar2wasm/tests/wasm-generation/sequences.rs

Fixes https://github.com/stacks-network/clarity-wasm/issues/320, https://github.com/stacks-network/clarity-wasm/issues/489 and https://github.com/stacks-network/clarity-wasm/issues/368.
When generating recursive type signature for props, if the value is too large fall back to the child prop (ie, skip recursion step). For `any_sequence` just add `prop_filter` (otherwise we would need to use a fixed safe type, eg a list of bools).
Tested by bumping `max_local_rejects` to `1<<20` and generating props from `prop_signature().prop_filter("ignore small", |t| t.size().unwrap() > 1 << 20)` (and similar for `any_sequence`): without the fix, we get `Result::unwrap() on an Err value: ValueTooLarge` (eg, from the list variant in `prop_signature`), with the fix no large values are found (`Too many …

Avoid generating too large prop types

---

clar2wasm/src/words/conditionals.rs

Validate nested logical functions

test nested logical functions

---

clar2wasm/src/wasm_utils.rs
clar2wasm/src/words/traits.rs

When reading a `CallableType` back from wasm avoid coercing it to a contract `Principal` (see changed test for an example of this).

Avoid eliding CallableType when reading back from wasm

---

.github/workflows/ci.yaml
clar2wasm/src/datastore.rs
clar2wasm/src/lib.rs
clar2wasm/src/tools.rs
clar2wasm/src/wasm_utils.rs
clar2wasm/tests/wasm-generation/main.rs
clar2wasm/tests/wasm-generation/principal.rs
rust-toolchain.toml

Principal functions proptests

---

clar2wasm/tests/wasm-generation/consensus_buff.rs

test: remove the consensus-buff proptests for clarity1

---

clar2wasm/src/tools.rs
clar2wasm/src/words/bindings.rs
clar2wasm/src/words/blockinfo.rs
clar2wasm/src/words/consensus_buff.rs
clar2wasm/src/words/constants.rs
clar2wasm/src/words/data_vars.rs
clar2wasm/src/words/functions.rs
clar2wasm/src/words/maps.rs
clar2wasm/src/words/tokens.rs
clar2wasm/src/words/traits.rs
clar2wasm/tests/wasm-generation/blockinfo.rs
clar2wasm/tests/wasm-generation/consensus_buff.rs
clar2wasm/tests/wasm-generation/tokens.rs

fix #518 .
This PR adds feature gates to `crosscheck_with_epoch` function.
Also fix some tests to reflect the feature gate change.

test: feature gates on crosscheck_with_epoch

---

clar2wasm/src/wasm_generator.rs

Introspection function that have proven invaluable as i'm tracking down #496

Add a methods to debug stack contents and locals

---

clar2wasm/tests/wasm-generation/principal.rs

Fix #537 . Skip proptests that rely on a contract name that has the known [issue](https://github.com/stacks-network/stacks-core/issues/5330).

test: skip not valid principal-destruct? proptests

---

clar2wasm/src/tools.rs

This PR refactors the error handling logic in the `crosscheck_compare_only` function. By replacing sequential `assert` checks with a `match` expression, the code now:
- panics with both errors if the interpreted and compiled results fail simultaneously
- panics with the specific error when only one result fails
Related issue: #553

Refactor error handling in `crosscheck_compare_only`

---

clar2wasm/tests/standard/unit_tests.rs

There was a small piece of unsafe code to compute the number of bytes a "pretend char" would use in UTF-8.
Running this test with the release optimizations would send a SIGILL, which, weirdly enough, stalls the tests.
This PR removes the unsafe part and now the tests runs smoothly in release mode.

Remove the unsafe code in standard's unit tests

---

.github/workflows/ci.yaml
clar2wasm/src/datastore.rs

remove constraint to changes on markdown files

---

clar2wasm/src/wasm_generator.rs
clar2wasm/src/words/functions.rs

issue with duplicated define-read-only names

---

clar2wasm/benches/comparison.rs

In an effort to make the interpreter vs. webassembly benchmarks more representative, we add the `map_set_entries` benchmark, and modify the `fold_add_square` benchmark. These now, respectively, represent write-heavy and compute-heavy workloads, allowing us to compare the behavior of both runtimes under these regimes.
Since they were not representative of anything besides the overhead in executing a contract call, we remove all other benchmarks besides `add`.
We're left with 3 different benches:
- Compute, with `fold_add_square`
- Write, with `map_set_entries`
- Overhead, with `add`

Add comparative compute and write benchmarks

---

clar2wasm/src/tools.rs
clar2wasm/src/wasm_generator.rs
clar2wasm/src/wasm_utils.rs

Fix clippy 1.84 warnings

---

clar2wasm/src/words/sequences.rs

This PR introduces test cases for all functions within the `map` function.
Fixes: #595

Add test cases for `map` function

---

clar2wasm/benches/comparison.rs

A simple oracle contract is added as a benchmark. This is a more mixed workload, with each price update consisting of a read, a write, and some computation throughout.

Add oracle benchmark

---

clar2wasm/src/words/sequences.rs

Optimize UTF-8 sequences calculations using bitwise operations.
Fix https://github.com/stacks-network/clarity-wasm/issues/589

optimize UTF-8 sequence computations using bitwise shift

---

Cargo.lock
clar2wasm/src/wasm_generator.rs
clar2wasm/src/wasm_utils.rs
clar2wasm/tests/standard/unit_tests.rs
clar2wasm/tests/wasm-generation/main.rs
clar2wasm/tests/wasm-generation/principal.rs

Adapt the code to a recent refactor on `StacksAddress` and `PrincipalData` -> https://github.com/stacks-network/stacks-core/pull/5739/

adapt code to stacks-core refactor

---

clar2wasm/src/cost.rs
clar2wasm/src/cost/clar1.rs
clar2wasm/src/cost/clar2.rs
clar2wasm/src/wasm_generator.rs

cost-tracking: add support for clarity 1 and 2

---

clar2wasm/src/words/arithmetic.rs
clar2wasm/src/words/bitwise.rs
clar2wasm/src/words/buff_to_integer.rs
clar2wasm/src/words/comparison.rs
clar2wasm/src/words/conditionals.rs
clar2wasm/src/words/conversion.rs
clar2wasm/src/words/hashing.rs
clar2wasm/src/words/logical.rs
clar2wasm/src/words/noop.rs
clar2wasm/src/words/principal.rs
clar2wasm/src/words/stx.rs

cost-tracking: implement for all simple words

---

clar2wasm/src/words/bindings.rs
clar2wasm/src/words/blockinfo.rs
clar2wasm/src/words/conditionals.rs
clar2wasm/src/words/consensus_buff.rs
clar2wasm/src/words/contract.rs
clar2wasm/src/words/control_flow.rs
clar2wasm/src/words/data_vars.rs
clar2wasm/src/words/default_to.rs
clar2wasm/src/words/enums.rs
clar2wasm/src/words/equal.rs
clar2wasm/src/words/maps.rs
clar2wasm/src/words/noop.rs
clar2wasm/src/words/options.rs
clar2wasm/src/words/principal.rs
clar2wasm/src/words/print.rs
clar2wasm/src/words/responses.rs
clar2wasm/src/words/secp256k1.rs
clar2wasm/src/words/sequences.rs
clar2wasm/src/words/stx.rs
clar2wasm/src/words/tokens.rs
clar2wasm/src/words/tuples.rs

cost-tracking: implement all complex words

---

clar2wasm/src/error_mapping.rs

fix: handle cost overruns in `from_runtime_error_code`

---

.github/workflows/ci.yaml
clar2wasm/build.rs
clar2wasm/scripts/boot-contracts-compile.sh
clar2wasm/src/wasm_generator.rs

In order to increase compatibility with source immutable build systems like nix and guix the source directory should not be changed in the build process.
Solves #626
Serves https://github.com/stacks-network/stacks-core/issues/5807

No longer modifiying source files in build process

---

clar2wasm/src/initialize.rs

This change needs to be reverted, as it adds an additional call to `global_context.rollback()`, which in turn disrupts the function call context.

fix rollback handling in case of a runtime error

---

Cargo.lock
clar2wasm/src/bin/utils/mod.rs
clar2wasm/src/tools.rs

Add missing StacksEpochId::Epoch32.

Fix missing epoch

---

clar2wasm/src/wasm_generator.rs
clar2wasm/src/words/constants.rs

Fixes #709 
This PR changes the definition of the field `constants` in `WasmGenerator` to save the type that was used when traversing the constant.
Then, in constant lookup, we use that original type to read it, then we duck-type to the expected type.

Constants lookup needs duck-typing
